info:
  name: "HalfTheme"
  identifier: "halftheme"
  description: "A modern, premium UI for Pterodactyl with glassmorphism, custom components and neon colors."
  version: "2.0.0"
  target: "*"
  author: "HalfTheme"
  icon: ""
  website: "https://github.com/Thiagonox/halftheme"
  flags: ""

admin:
  view: "views/admin/index.blade.php"
  controller: ""
  css: "public/css/halftheme.css"
  wrapper: ""

dashboard:
  css: "public/css/halftheme.css"
  wrapper: "views/wrapper/dashboard.blade.php"

components: "components.yml"

data:
  directory: ""
  public: "public"

console: ""
requests: ""
views: "views"
app: "components"

routers:
  application: ""
  client: ""
  web: ""

database:
  migrations: ""
