info:
  name: "HalfTheme"
  identifier: "halftheme"
  description: "A modern, clean theme for Pterodactyl with vibrant neon colors (Magenta/Cyan) and shadcn-inspired design system."
  version: "1.0.0"
  target: "*"
  author: "HalfTheme"
  icon: ""
  website: "https://github.com/Thiagonox/halftheme"
  flags: ""

admin:
  view: "views/admin/index.blade.php"
  controller: ""
  css: "public/css/halftheme.css"
  wrapper: ""

dashboard:
  css: "public/css/halftheme.css"
  wrapper: "views/wrapper/dashboard.blade.php"

components: ""

data:
  directory: ""
  public: "public"

console: ""
requests: ""
views: "views"
app: ""

routers:
  application: ""
  client: ""
  web: ""

database:
  migrations: ""
